export const mockEvents = [
  {
    title: 'Tech Conference 2024',
    description: 'A conference about the latest trends in technology.',
    eventDate: '2024-10-10',
    organizer: 'Tech World',
  },
  {
    title: 'React Summit',
    description: 'A summit for React enthusiasts and developers.',
    eventDate: '2024-10-15',
    organizer: 'React Community',
  },
  {
    title: 'JavaScript Meetup',
    description: 'A meetup to discuss JavaScript and web development.',
    eventDate: '2024-09-30',
    organizer: 'JS Devs',
  },
  {
    title: 'AI Symposium',
    description: 'Exploring the future of Artificial Intelligence.',
    eventDate: '2024-11-05',
    organizer: 'AI Labs',
  },
  {
    title: 'UX/UI Design Workshop',
    description: 'Hands-on workshop for UX/UI designers.',
    eventDate: '2024-09-25',
    organizer: 'Design Studio',
  },
  {
    title: 'Node.js Conference',
    description: 'Conference focused on Node.js and server-side development.',
    eventDate: '2024-12-12',
    organizer: 'Node Masters',
  },
  {
    title: 'Full-Stack Dev Bootcamp',
    description: 'A bootcamp covering full-stack development with modern tools.',
    eventDate: '2024-10-01',
    organizer: 'Dev Academy',
  },
  {
    title: 'Cybersecurity Expo',
    description: 'An expo for cybersecurity professionals and enthusiasts.',
    eventDate: '2024-11-20',
    organizer: 'CyberSec Group',
  },
  {
    title: 'DevOps Workshop',
    description: 'Learn the best practices of DevOps in this workshop.',
    eventDate: '2024-09-22',
    organizer: 'DevOps Experts',
  },
  {
    title: 'Cloud Computing Conference',
    description: 'Conference focusing on cloud computing technologies.',
    eventDate: '2024-12-03',
    organizer: 'Cloud Masters',
  },
  {
    title: 'Python Summit',
    description: 'A summit for Python developers.',
    eventDate: '2024-10-18',
    organizer: 'PyDev',
  },
  {
    title: 'Data Science Conference',
    description: 'The latest trends and technologies in data science.',
    eventDate: '2024-11-25',
    organizer: 'Data Academy',
  },
  {
    title: 'Blockchain Meetup',
    description: 'Discussion and networking event for blockchain developers.',
    eventDate: '2024-12-15',
    organizer: 'Blockchain Hub',
  },
  {
    title: 'Product Management Workshop',
    description: 'A workshop for aspiring product managers.',
    eventDate: '2024-09-28',
    organizer: 'Product Masters',
  },
  {
    title: 'Startup Pitch Day',
    description: 'Pitch your startup idea to investors.',
    eventDate: '2024-10-20',
    organizer: 'Startup Network',
  },
  {
    title: 'Web Development Crash Course',
    description: 'An intensive course on modern web development.',
    eventDate: '2024-11-01',
    organizer: 'Web Academy',
  },
  {
    title: 'Game Development Conference',
    description: 'Conference on the latest in game development technologies.',
    eventDate: '2024-12-10',
    organizer: 'Game Devs',
  },
  {
    title: 'Entrepreneurship Summit',
    description: 'A summit for aspiring and current entrepreneurs.',
    eventDate: '2024-09-24',
    organizer: 'Entrepreneurs Hub',
  },
  {
    title: 'Marketing Strategies Workshop',
    description: 'Learn the latest marketing strategies in this workshop.',
    eventDate: '2024-10-07',
    organizer: 'Marketing Pros',
  },
  {
    title: 'E-commerce Expo',
    description: 'Expo focusing on the latest trends in e-commerce.',
    eventDate: '2024-11-30',
    organizer: 'E-commerce World',
  },
  {
    title: 'DevConf 2024',
    description: 'Annual conference for software developers.',
    eventDate: '2024-10-05',
    organizer: 'Dev Network',
  },
  {
    title: 'Startup Networking Event',
    description: 'Networking event for startup founders and investors.',
    eventDate: '2024-09-29',
    organizer: 'Startup Hub',
  },
  {
    title: 'Tech Innovations Forum',
    description: 'Forum discussing the latest tech innovations.',
    eventDate: '2024-11-10',
    organizer: 'Innovators Forum',
  },
  {
    title: 'Tech Forum',
    description: 'Exploring the latest tech innovations',
    eventDate: '2024-12-20',
    organizer: 'Tech Forum',
  },
  {
    title: 'Tech Conference 2024',
    description: 'A conference about the latest trends in technology.',
    eventDate: '2024-10-10',
    organizer: 'Tech World',
  },
  {
    title: 'React Summit',
    description: 'A summit for React enthusiasts and developers.',
    eventDate: '2024-10-15',
    organizer: 'React Community',
  },
  {
    title: 'JavaScript Meetup',
    description: 'A meetup to discuss JavaScript and web development.',
    eventDate: '2024-09-30',
    organizer: 'JS Devs',
  },
  {
    title: 'AI Symposium',
    description: 'Exploring the future of Artificial Intelligence.',
    eventDate: '2024-11-05',
    organizer: 'AI Labs',
  },
  {
    title: 'UX/UI Design Workshop',
    description: 'Hands-on workshop for UX/UI designers.',
    eventDate: '2024-09-25',
    organizer: 'Design Studio',
  },
  {
    title: 'Node.js Conference',
    description: 'Conference focused on Node.js and server-side development.',
    eventDate: '2024-12-12',
    organizer: 'Node Masters',
  },
  {
    title: 'Full-Stack Dev Bootcamp',
    description: 'A bootcamp covering full-stack development with modern tools.',
    eventDate: '2024-10-01',
    organizer: 'Dev Academy',
  },
  {
    title: 'Cybersecurity Expo',
    description: 'An expo for cybersecurity professionals and enthusiasts.',
    eventDate: '2024-11-20',
    organizer: 'CyberSec Group',
  },
  {
    title: 'DevOps Workshop',
    description: 'Learn the best practices of DevOps in this workshop.',
    eventDate: '2024-09-22',
    organizer: 'DevOps Experts',
  },
  {
    title: 'Cloud Computing Conference',
    description: 'Conference focusing on cloud computing technologies.',
    eventDate: '2024-12-03',
    organizer: 'Cloud Masters',
  },
  {
    title: 'Python Summit',
    description: 'A summit for Python developers.',
    eventDate: '2024-10-18',
    organizer: 'PyDev',
  },
  {
    title: 'Data Science Conference',
    description: 'The latest trends and technologies in data science.',
    eventDate: '2024-11-25',
    organizer: 'Data Academy',
  },
  {
    title: 'Blockchain Meetup',
    description: 'Discussion and networking event for blockchain developers.',
    eventDate: '2024-12-15',
    organizer: 'Blockchain Hub',
  },
  {
    title: 'Product Management Workshop',
    description: 'A workshop for aspiring product managers.',
    eventDate: '2024-09-28',
    organizer: 'Product Masters',
  },
  {
    title: 'Startup Pitch Day',
    description: 'Pitch your startup idea to investors.',
    eventDate: '2024-10-20',
    organizer: 'Startup Network',
  },
  {
    title: 'Web Development Crash Course',
    description: 'An intensive course on modern web development.',
    eventDate: '2024-11-01',
    organizer: 'Web Academy',
  },
  {
    title: 'Game Development Conference',
    description: 'Conference on the latest in game development technologies.',
    eventDate: '2024-12-10',
    organizer: 'Game Devs',
  },
  {
    title: 'Entrepreneurship Summit',
    description: 'A summit for aspiring and current entrepreneurs.',
    eventDate: '2024-09-24',
    organizer: 'Entrepreneurs Hub',
  },
  {
    title: 'Marketing Strategies Workshop',
    description: 'Learn the latest marketing strategies in this workshop.',
    eventDate: '2024-10-07',
    organizer: 'Marketing Pros',
  },
  {
    title: 'E-commerce Expo',
    description: 'Expo focusing on the latest trends in e-commerce.',
    eventDate: '2024-11-30',
    organizer: 'E-commerce World',
  },
  {
    title: 'DevConf 2024',
    description: 'Annual conference for software developers.',
    eventDate: '2024-10-05',
    organizer: 'Dev Network',
  },
  {
    title: 'Startup Networking Event',
    description: 'Networking event for startup founders and investors.',
    eventDate: '2024-09-29',
    organizer: 'Startup Hub',
  },
  {
    title: 'Tech Innovations Forum',
    description: 'Forum discussing the latest tech innovations.',
    eventDate: '2024-11-10',
    organizer: 'Innovators Forum',
  },
  {
    title: 'Tech Forum',
    description: 'Exploring the latest tech innovations',
    eventDate: '2024-12-20',
    organizer: 'Tech Forum',
  },
  {
    title: 'Tech Conference 2024',
    description: 'A conference about the latest trends in technology.',
    eventDate: '2024-10-10',
    organizer: 'Tech World',
  },
  {
    title: 'React Summit',
    description: 'A summit for React enthusiasts and developers.',
    eventDate: '2024-10-15',
    organizer: 'React Community',
  },
  {
    title: 'JavaScript Meetup',
    description: 'A meetup to discuss JavaScript and web development.',
    eventDate: '2024-09-30',
    organizer: 'JS Devs',
  },
  {
    title: 'AI Symposium',
    description: 'Exploring the future of Artificial Intelligence.',
    eventDate: '2024-11-05',
    organizer: 'AI Labs',
  },
  {
    title: 'UX/UI Design Workshop',
    description: 'Hands-on workshop for UX/UI designers.',
    eventDate: '2024-09-25',
    organizer: 'Design Studio',
  },
  {
    title: 'Node.js Conference',
    description: 'Conference focused on Node.js and server-side development.',
    eventDate: '2024-12-12',
    organizer: 'Node Masters',
  },
  {
    title: 'Full-Stack Dev Bootcamp',
    description: 'A bootcamp covering full-stack development with modern tools.',
    eventDate: '2024-10-01',
    organizer: 'Dev Academy',
  },
  {
    title: 'Cybersecurity Expo',
    description: 'An expo for cybersecurity professionals and enthusiasts.',
    eventDate: '2024-11-20',
    organizer: 'CyberSec Group',
  },
  {
    title: 'DevOps Workshop',
    description: 'Learn the best practices of DevOps in this workshop.',
    eventDate: '2024-09-22',
    organizer: 'DevOps Experts',
  },
  {
    title: 'Cloud Computing Conference',
    description: 'Conference focusing on cloud computing technologies.',
    eventDate: '2024-12-03',
    organizer: 'Cloud Masters',
  },
  {
    title: 'Python Summit',
    description: 'A summit for Python developers.',
    eventDate: '2024-10-18',
    organizer: 'PyDev',
  },
  {
    title: 'Data Science Conference',
    description: 'The latest trends and technologies in data science.',
    eventDate: '2024-11-25',
    organizer: 'Data Academy',
  },
  {
    title: 'Blockchain Meetup',
    description: 'Discussion and networking event for blockchain developers.',
    eventDate: '2024-12-15',
    organizer: 'Blockchain Hub',
  },
  {
    title: 'Product Management Workshop',
    description: 'A workshop for aspiring product managers.',
    eventDate: '2024-09-28',
    organizer: 'Product Masters',
  },
  {
    title: 'Startup Pitch Day',
    description: 'Pitch your startup idea to investors.',
    eventDate: '2024-10-20',
    organizer: 'Startup Network',
  },
  {
    title: 'Web Development Crash Course',
    description: 'An intensive course on modern web development.',
    eventDate: '2024-11-01',
    organizer: 'Web Academy',
  },
  {
    title: 'Game Development Conference',
    description: 'Conference on the latest in game development technologies.',
    eventDate: '2024-12-10',
    organizer: 'Game Devs',
  },
  {
    title: 'Entrepreneurship Summit',
    description: 'A summit for aspiring and current entrepreneurs.',
    eventDate: '2024-09-24',
    organizer: 'Entrepreneurs Hub',
  },
  {
    title: 'Marketing Strategies Workshop',
    description: 'Learn the latest marketing strategies in this workshop.',
    eventDate: '2024-10-07',
    organizer: 'Marketing Pros',
  },
  {
    title: 'E-commerce Expo',
    description: 'Expo focusing on the latest trends in e-commerce.',
    eventDate: '2024-11-30',
    organizer: 'E-commerce World',
  },
  {
    title: 'DevConf 2024',
    description: 'Annual conference for software developers.',
    eventDate: '2024-10-05',
    organizer: 'Dev Network',
  },
  {
    title: 'Startup Networking Event',
    description: 'Networking event for startup founders and investors.',
    eventDate: '2024-09-29',
    organizer: 'Startup Hub',
  },
  {
    title: 'Tech Innovations Forum',
    description: 'Forum discussing the latest tech innovations.',
    eventDate: '2024-11-10',
    organizer: 'Innovators Forum',
  },
  {
    title: 'Tech Forum',
    description: 'Exploring the latest tech innovations',
    eventDate: '2024-12-20',
    organizer: 'Tech Forum',
  },
  {
    title: 'Tech Conference 2024',
    description: 'A conference about the latest trends in technology.',
    eventDate: '2024-10-10',
    organizer: 'Tech World',
  },
  {
    title: 'React Summit',
    description: 'A summit for React enthusiasts and developers.',
    eventDate: '2024-10-15',
    organizer: 'React Community',
  },
  {
    title: 'JavaScript Meetup',
    description: 'A meetup to discuss JavaScript and web development.',
    eventDate: '2024-09-30',
    organizer: 'JS Devs',
  },
  {
    title: 'AI Symposium',
    description: 'Exploring the future of Artificial Intelligence.',
    eventDate: '2024-11-05',
    organizer: 'AI Labs',
  },
  {
    title: 'UX/UI Design Workshop',
    description: 'Hands-on workshop for UX/UI designers.',
    eventDate: '2024-09-25',
    organizer: 'Design Studio',
  },
  {
    title: 'Node.js Conference',
    description: 'Conference focused on Node.js and server-side development.',
    eventDate: '2024-12-12',
    organizer: 'Node Masters',
  },
  {
    title: 'Full-Stack Dev Bootcamp',
    description: 'A bootcamp covering full-stack development with modern tools.',
    eventDate: '2024-10-01',
    organizer: 'Dev Academy',
  },
  {
    title: 'Cybersecurity Expo',
    description: 'An expo for cybersecurity professionals and enthusiasts.',
    eventDate: '2024-11-20',
    organizer: 'CyberSec Group',
  },
  {
    title: 'DevOps Workshop',
    description: 'Learn the best practices of DevOps in this workshop.',
    eventDate: '2024-09-22',
    organizer: 'DevOps Experts',
  },
  {
    title: 'Cloud Computing Conference',
    description: 'Conference focusing on cloud computing technologies.',
    eventDate: '2024-12-03',
    organizer: 'Cloud Masters',
  },
  {
    title: 'Python Summit',
    description: 'A summit for Python developers.',
    eventDate: '2024-10-18',
    organizer: 'PyDev',
  },
  {
    title: 'Data Science Conference',
    description: 'The latest trends and technologies in data science.',
    eventDate: '2024-11-25',
    organizer: 'Data Academy',
  },
  {
    title: 'Blockchain Meetup',
    description: 'Discussion and networking event for blockchain developers.',
    eventDate: '2024-12-15',
    organizer: 'Blockchain Hub',
  },
  {
    title: 'Product Management Workshop',
    description: 'A workshop for aspiring product managers.',
    eventDate: '2024-09-28',
    organizer: 'Product Masters',
  },
  {
    title: 'Startup Pitch Day',
    description: 'Pitch your startup idea to investors.',
    eventDate: '2024-10-20',
    organizer: 'Startup Network',
  },
  {
    title: 'Web Development Crash Course',
    description: 'An intensive course on modern web development.',
    eventDate: '2024-11-01',
    organizer: 'Web Academy',
  },
  {
    title: 'Game Development Conference',
    description: 'Conference on the latest in game development technologies.',
    eventDate: '2024-12-10',
    organizer: 'Game Devs',
  },
  {
    title: 'Entrepreneurship Summit',
    description: 'A summit for aspiring and current entrepreneurs.',
    eventDate: '2024-09-24',
    organizer: 'Entrepreneurs Hub',
  },
  {
    title: 'Marketing Strategies Workshop',
    description: 'Learn the latest marketing strategies in this workshop.',
    eventDate: '2024-10-07',
    organizer: 'Marketing Pros',
  },
  {
    title: 'E-commerce Expo',
    description: 'Expo focusing on the latest trends in e-commerce.',
    eventDate: '2024-11-30',
    organizer: 'E-commerce World',
  },
  {
    title: 'DevConf 2024',
    description: 'Annual conference for software developers.',
    eventDate: '2024-10-05',
    organizer: 'Dev Network',
  },
  {
    title: 'Startup Networking Event',
    description: 'Networking event for startup founders and investors.',
    eventDate: '2024-09-29',
    organizer: 'Startup Hub',
  },
  {
    title: 'Tech Innovations Forum',
    description: 'Forum discussing the latest tech innovations.',
    eventDate: '2024-11-10',
    organizer: 'Innovators Forum',
  },
  {
    title: 'Tech Forum',
    description: 'Exploring the latest tech innovations',
    eventDate: '2024-12-20',
    organizer: 'Tech Forum',
  },
  {
    title: 'Tech Conference 2024',
    description: 'A conference about the latest trends in technology.',
    eventDate: '2024-10-10',
    organizer: 'Tech World',
  },
  {
    title: 'React Summit',
    description: 'A summit for React enthusiasts and developers.',
    eventDate: '2024-10-15',
    organizer: 'React Community',
  },
  {
    title: 'JavaScript Meetup',
    description: 'A meetup to discuss JavaScript and web development.',
    eventDate: '2024-09-30',
    organizer: 'JS Devs',
  },
  {
    title: 'AI Symposium',
    description: 'Exploring the future of Artificial Intelligence.',
    eventDate: '2024-11-05',
    organizer: 'AI Labs',
  },
  {
    title: 'UX/UI Design Workshop',
    description: 'Hands-on workshop for UX/UI designers.',
    eventDate: '2024-09-25',
    organizer: 'Design Studio',
  },
  {
    title: 'Node.js Conference',
    description: 'Conference focused on Node.js and server-side development.',
    eventDate: '2024-12-12',
    organizer: 'Node Masters',
  },
  {
    title: 'Full-Stack Dev Bootcamp',
    description: 'A bootcamp covering full-stack development with modern tools.',
    eventDate: '2024-10-01',
    organizer: 'Dev Academy',
  },
  {
    title: 'Cybersecurity Expo',
    description: 'An expo for cybersecurity professionals and enthusiasts.',
    eventDate: '2024-11-20',
    organizer: 'CyberSec Group',
  },
  {
    title: 'DevOps Workshop',
    description: 'Learn the best practices of DevOps in this workshop.',
    eventDate: '2024-09-22',
    organizer: 'DevOps Experts',
  },
  {
    title: 'Cloud Computing Conference',
    description: 'Conference focusing on cloud computing technologies.',
    eventDate: '2024-12-03',
    organizer: 'Cloud Masters',
  },
  {
    title: 'Python Summit',
    description: 'A summit for Python developers.',
    eventDate: '2024-10-18',
    organizer: 'PyDev',
  },
  {
    title: 'Data Science Conference',
    description: 'The latest trends and technologies in data science.',
    eventDate: '2024-11-25',
    organizer: 'Data Academy',
  },
  {
    title: 'Blockchain Meetup',
    description: 'Discussion and networking event for blockchain developers.',
    eventDate: '2024-12-15',
    organizer: 'Blockchain Hub',
  },
  {
    title: 'Product Management Workshop',
    description: 'A workshop for aspiring product managers.',
    eventDate: '2024-09-28',
    organizer: 'Product Masters',
  },
  {
    title: 'Startup Pitch Day',
    description: 'Pitch your startup idea to investors.',
    eventDate: '2024-10-20',
    organizer: 'Startup Network',
  },
  {
    title: 'Web Development Crash Course',
    description: 'An intensive course on modern web development.',
    eventDate: '2024-11-01',
    organizer: 'Web Academy',
  },
  {
    title: 'Game Development Conference',
    description: 'Conference on the latest in game development technologies.',
    eventDate: '2024-12-10',
    organizer: 'Game Devs',
  },
  {
    title: 'Entrepreneurship Summit',
    description: 'A summit for aspiring and current entrepreneurs.',
    eventDate: '2024-09-24',
    organizer: 'Entrepreneurs Hub',
  },
  {
    title: 'Marketing Strategies Workshop',
    description: 'Learn the latest marketing strategies in this workshop.',
    eventDate: '2024-10-07',
    organizer: 'Marketing Pros',
  },
  {
    title: 'E-commerce Expo',
    description: 'Expo focusing on the latest trends in e-commerce.',
    eventDate: '2024-11-30',
    organizer: 'E-commerce World',
  },
  {
    title: 'DevConf 2024',
    description: 'Annual conference for software developers.',
    eventDate: '2024-10-05',
    organizer: 'Dev Network',
  },
  {
    title: 'Startup Networking Event',
    description: 'Networking event for startup founders and investors.',
    eventDate: '2024-09-29',
    organizer: 'Startup Hub',
  },
  {
    title: 'Tech Innovations Forum',
    description: 'Forum discussing the latest tech innovations.',
    eventDate: '2024-11-10',
    organizer: 'Innovators Forum',
  },
  {
    title: 'Tech Forum',
    description: 'Exploring the latest tech innovations',
    eventDate: '2024-12-20',
    organizer: 'Tech Forum',
  },
  {
    title: 'Tech Conference 2024',
    description: 'A conference about the latest trends in technology.',
    eventDate: '2024-10-10',
    organizer: 'Tech World',
  },
  {
    title: 'React Summit',
    description: 'A summit for React enthusiasts and developers.',
    eventDate: '2024-10-15',
    organizer: 'React Community',
  },
  {
    title: 'JavaScript Meetup',
    description: 'A meetup to discuss JavaScript and web development.',
    eventDate: '2024-09-30',
    organizer: 'JS Devs',
  },
  {
    title: 'AI Symposium',
    description: 'Exploring the future of Artificial Intelligence.',
    eventDate: '2024-11-05',
    organizer: 'AI Labs',
  },
  {
    title: 'UX/UI Design Workshop',
    description: 'Hands-on workshop for UX/UI designers.',
    eventDate: '2024-09-25',
    organizer: 'Design Studio',
  },
  {
    title: 'Node.js Conference',
    description: 'Conference focused on Node.js and server-side development.',
    eventDate: '2024-12-12',
    organizer: 'Node Masters',
  },
  {
    title: 'Full-Stack Dev Bootcamp',
    description: 'A bootcamp covering full-stack development with modern tools.',
    eventDate: '2024-10-01',
    organizer: 'Dev Academy',
  },
  {
    title: 'Cybersecurity Expo',
    description: 'An expo for cybersecurity professionals and enthusiasts.',
    eventDate: '2024-11-20',
    organizer: 'CyberSec Group',
  },
  {
    title: 'DevOps Workshop',
    description: 'Learn the best practices of DevOps in this workshop.',
    eventDate: '2024-09-22',
    organizer: 'DevOps Experts',
  },
  {
    title: 'Cloud Computing Conference',
    description: 'Conference focusing on cloud computing technologies.',
    eventDate: '2024-12-03',
    organizer: 'Cloud Masters',
  },
  {
    title: 'Python Summit',
    description: 'A summit for Python developers.',
    eventDate: '2024-10-18',
    organizer: 'PyDev',
  },
  {
    title: 'Data Science Conference',
    description: 'The latest trends and technologies in data science.',
    eventDate: '2024-11-25',
    organizer: 'Data Academy',
  },
  {
    title: 'Blockchain Meetup',
    description: 'Discussion and networking event for blockchain developers.',
    eventDate: '2024-12-15',
    organizer: 'Blockchain Hub',
  },
  {
    title: 'Product Management Workshop',
    description: 'A workshop for aspiring product managers.',
    eventDate: '2024-09-28',
    organizer: 'Product Masters',
  },
  {
    title: 'Startup Pitch Day',
    description: 'Pitch your startup idea to investors.',
    eventDate: '2024-10-20',
    organizer: 'Startup Network',
  },
  {
    title: 'Web Development Crash Course',
    description: 'An intensive course on modern web development.',
    eventDate: '2024-11-01',
    organizer: 'Web Academy',
  },
  {
    title: 'Game Development Conference',
    description: 'Conference on the latest in game development technologies.',
    eventDate: '2024-12-10',
    organizer: 'Game Devs',
  },
  {
    title: 'Entrepreneurship Summit',
    description: 'A summit for aspiring and current entrepreneurs.',
    eventDate: '2024-09-24',
    organizer: 'Entrepreneurs Hub',
  },
  {
    title: 'Marketing Strategies Workshop',
    description: 'Learn the latest marketing strategies in this workshop.',
    eventDate: '2024-10-07',
    organizer: 'Marketing Pros',
  },
  {
    title: 'E-commerce Expo',
    description: 'Expo focusing on the latest trends in e-commerce.',
    eventDate: '2024-11-30',
    organizer: 'E-commerce World',
  },
  {
    title: 'DevConf 2024',
    description: 'Annual conference for software developers.',
    eventDate: '2024-10-05',
    organizer: 'Dev Network',
  },
  {
    title: 'Startup Networking Event',
    description: 'Networking event for startup founders and investors.',
    eventDate: '2024-09-29',
    organizer: 'Startup Hub',
  },
  {
    title: 'Tech Innovations Forum',
    description: 'Forum discussing the latest tech innovations.',
    eventDate: '2024-11-10',
    organizer: 'Innovators Forum',
  },
  {
    title: 'Tech Forum',
    description: 'Exploring the latest tech innovations',
    eventDate: '2024-12-20',
    organizer: 'Tech Forum',
  },
];
